name: code_review

on:
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          LANGUAGE: Korean

        with:
          path: './.github/workflows/review.md'  # 생성할 파일 경로
          write-mode: overwrite  # 파일을 덮어쓸지 여부